@WorkflowApp.Api_HostAddress=http://localhost:5071
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ0ZXN0dXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFwcGxpY2FudCIsImRpc3BsYXlOYW1lIjoiVGVzdCBVc2VyIiwiZXhwIjoxNzczOTk2MTE1LCJpc3MiOiJXb3JrZmxvd0FwcC5BcGkiLCJhdWQiOiJXb3JrZmxvd0FwcC5DbGllbnQifQ.xTz85FNDZ6vaxBhEtu9gHm-D8cgfYhJTUx5djmPaj1M

### register
POST {{WorkflowApp.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "loginId": "testuser",
  "displayName": "Test User",
  "password": "Password123"
}

### login
POST {{WorkflowApp.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "loginId": "testuser",
  "password": "Password123"
}

### token（手動で貼る）
GET {{WorkflowApp.Api_HostAddress}}/api/sample/me
Authorization: Bearer {{token}}